openapi: 3.0.1
info:
  title: '@jupiterone/graph-cisco-umbrella'
  description: A JupiterOne Integration for https://umbrella.cisco.com/
  x-cortex-git:
    github:
      repository: JupiterOne/graph-cisco-umbrella
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-cisco-umbrella'
  x-cortex-service-groups:
    - tier-4
